# Generated by Django 5.0.6 on 2024-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('categoria', models.TextField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('preco', models.IntegerField()),
            ],
        ),
    ]
