# Generated by Django 5.0.6 on 2024-05-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_estoque", "0002_cargo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="permissao",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
