# Generated by Django 5.0.6 on 2024-07-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0002_alter_cargo_nome_alter_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='nome',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='permissao',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='chave_acesso',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='senha',
            field=models.TextField(max_length=255),
        ),
    ]
