# Generated by Django 5.0.6 on 2024-07-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estoque', '0003_alter_cargo_nome_alter_cargo_permissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='permissao',
            field=models.IntegerField(),
        ),
    ]
