# Generated by Django 5.0.6 on 2024-05-14 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_estoque", "0004_alter_user_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cargo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios",
                to="app_estoque.cargo",
            ),
        ),
    ]
