# Generated by Django 5.0.6 on 2024-07-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_estoque", "0007_remove_user_senha_user_groups_user_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="user",
            name="chave_acesso",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
