# Generated by Django 5.0.6 on 2024-07-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_estoque", "0009_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="senha",
            field=models.CharField(default="temp_password", max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
